title: Apocalypse Made Easy!
email: info@apocalypsemadeeasy.com
description: A free, outdoor, team survival training game that runs in your phone's web browser. Play now in Vancouver and Kelowna.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title
destination: ./docs

# Build settings
markdown: kramdown