title: Apocalypse Made Easy!
email: info@apocalypsemadeeasy.com
description: An outdoor, team-based apocalypse training course that runs in your phone's browser. Public beta now open in Vancouver.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title
destination: ./docs

# Build settings
markdown: kramdown